export { default as homeIcon } from './home_icon.svg';
export { default as chevronDown } from './chevron_down_icon.svg';
export { default as instagram } from './instagram_icon.svg';
// export { default as logoGreen } from './logo_green.svg';
// export { default as OnlylogoGreen } from './Only_logo_green.svg';
export { default as OnlylogoUob } from './Only_logo_uob.png';
export { default as UobLogo } from './uob_logo.png';
export { default as OnlylogoGreen } from './Only_logo_green.svg';
export { default as logoGreen } from './logo_green.svg';
export { default as logoWhite } from './logo_white.svg';
export { default as sendIcon } from './send_icon.svg';
export { default as mapLayer } from './map_layer.png';
export { default as googleMapIcon } from './google_map_icon.png';
export { default as baiDuMapIcon } from './baidu_map_icon.png';
export { default as backgroundFAQTop } from './background_faq_top_Uob.png';
export { default as backgroundFAQBottom } from './background_faq_bottom_Uob.png';
export { default as supportPageBackground } from './support_img.png';
export { default as bgNotificationTop } from './bg_notification_top.png';
export { default as bgNotificationBottom } from './bg_notification_bottom.png';
export { default as checkIcon } from './check_icon.svg';
export { default as removeIcon } from './remove_icon.svg';
export { default as notificationIcon } from './notification_icon.svg';
export { default as dashboardStatisticCardBlue } from './dashboard_statistic_card_blue.svg';
export { default as dashboardStatisticCardYellow } from './dashboard_statistic_card_yellow.svg';
export { default as dashboardStatisticCardGreen } from './dashboard_statistic_card_green.svg';
export { default as dashboardStatisticCardPurple } from './dashboard_statistic_card_purple.svg';
export { default as dashboardOffice } from './dashboard_office.svg';
export { default as dashboardUser } from './dashboard_user.svg';
export { default as dashboardThunderbolt } from './dashboard_thunderbolt.svg';
export { default as dashboardFiletext } from './dashboard_filetext.svg';
// export { default as authBackground } from './greenfi.png';
export { default as ReportingGraphics } from './ReportingGraphics.svg';
export { default as emptyCompany } from './empty-company.svg';
